
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LINK5
 */
public class Indicator extends javax.swing.JFrame {

    /**
     * Creates new form Indicator
     */
    private Image url_red;
    private Image url_white;
    private KeyEvent evt;
    private int isActivated = -1;

    public Indicator() throws IOException {
        initComponents();
        this.loadImages();
        this.startEvent(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_capsLock = new javax.swing.JLabel();
        jLabel_blockNum = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel1.setText("CapsLock");

        jLabel2.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel2.setText("BloqNum");

        jLabel_capsLock.setText("jLabel4");

        jLabel_blockNum.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel_capsLock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel_blockNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_blockNum, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_capsLock, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadImages() {

        Image url_red = new ImageIcon(
                getClass().getResource("images/red_circle.png")
        ).getImage();

        Image url_white = new ImageIcon(
                getClass().getResource("images/white_circle.png")
        ).getImage();

        this.url_red = url_red;
        this.url_white = url_white;

    }

    private void startEvent(KeyEvent evt) {

        this.formKeyPressed(evt);
    }


    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:    
        if (this.isActivated != -1) {
            boolean capsActivo = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK);
            boolean numActivo = Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_NUM_LOCK);
            
            if (capsActivo) {                
                this.setStatusWindowActivated(KeyEvent.VK_CAPS_LOCK, false);
                //this.setStatusWindowActivated(KeyEvent.VK_CAPS_LOCK, false);
               this.setStatus("white",this.jLabel_capsLock);
            } else {
                
                this.setStatusWindowActivated(KeyEvent.VK_CAPS_LOCK, true);
                //this.setStatusWindowActivated(KeyEvent.VK_CAPS_LOCK, true);
                this.setStatus("red",this.jLabel_capsLock);

            }
            
            if (numActivo) {                
                this.setStatusWindowActivated(KeyEvent.VK_NUM_LOCK, false);
                //this.setStatusWindowActivated(KeyEvent.VK_NUM_LOCK, false);
               this.setStatus("white",this.jLabel_blockNum);
            } else {
                
                this.setStatusWindowActivated(KeyEvent.VK_NUM_LOCK, true);
                //this.setStatusWindowActivated(KeyEvent.VK_NUM_LOCK, true);
                this.setStatus("red",this.jLabel_blockNum);

            }

        }
        this.isActivated=1;
    }//GEN-LAST:event_formWindowActivated

    private void setStatusWindowActivated(int keyEvent,boolean status){
   
       Toolkit.getDefaultToolkit().setLockingKeyState(keyEvent, status);
       Toolkit.getDefaultToolkit().setLockingKeyState(keyEvent, status);
    
    }
      private void setStatus(String type,JLabel label){
      
           if(type.equalsIgnoreCase("red")){
                Image img = new ImageIcon(url_red).getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
                label.setIcon(img2);
                label.repaint();
           }else{
           
                Image img = new ImageIcon(url_white).getImage();
                ImageIcon img2 = new ImageIcon(img.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH));
                label.setIcon(img2);
                label.repaint();
           }
      
      
      
      }
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

        boolean capsActivo = Toolkit.getDefaultToolkit().getLockingKeyState(evt.VK_CAPS_LOCK);

         if (capsActivo) {
            this.setStatus("red", this.jLabel_capsLock);            
        } else {
            this.setStatus("white", this.jLabel_capsLock);                        
        }

        boolean capsActivo2 = Toolkit.getDefaultToolkit().getLockingKeyState(evt.VK_NUM_LOCK);
        if (capsActivo2) {
            this.setStatus("red", this.jLabel_blockNum);                       
        } else {
            this.setStatus("white", this.jLabel_blockNum);                                   
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Indicator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Indicator().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Indicator.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_blockNum;
    private javax.swing.JLabel jLabel_capsLock;
    // End of variables declaration//GEN-END:variables
}
